[colors.bright]
black = "#505354"
blue = "#0c73c2"
cyan = "#899ca1"
green = "#b6e354"
magenta = "#9e6ffe"
red = "#ff5995"
white = "#ffffff"
yellow = "#feed6c"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#1b1b1b"
blue = "#4e82aa"
cyan = "#465457"
green = "#82b414"
magenta = "#8c54fe"
red = "#f92672"
white = "#cccccc"
yellow = "#fd971f"

[colors.primary]
background = "#121212"
foreground = "#a0a0a0"

[font]
size = 10.0

[font.bold]
family = "FiraMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraMono Nerd Font"
style = "Italic"

[font.normal]
family = "FiraMono Nerd Font"
style = "Regular"

[shell]
program = "bash"
args = ["-c", "tmux a || tmux"]
