#!/bin/bash

set -e

here="$(dirname "${BASH_SOURCE[0]}")"

if [[ ! -f ${here}/colors ]] ; then
    cat > ${here}/colors <<-'EOF'
	#!/bin/bash

	# Uncomment to override prompt colors
	# PS1_FG1=30  # black
	# PS1_BG1=101 # red
	# PS1_FG2=97  # white
	# PS1_BG2=100 # gray
	EOF
fi

source /etc/os-release
OS_ID=${ID_LIKE:-$ID}

case ${OS_ID} in
    debian)
	if [[ -e /etc/wsl.conf ]] ; then
	    # Fix NPM proxy fuckery
	    npm_fix="1.1.1.1 registry.npmjs.org"
	    if ! grep -qF "${npm_fix}" /etc/hosts ; then
		echo $'\n'"${npm_fix}" | sudo tee -a /etc/hosts >/dev/null
	    fi
	fi

        sudo apt install --upgrade --quiet -y curl gcc neovim npm python3{,-pip} clang cmake
        npm list -g bash-language-server 2>/dev/null | grep -q bash-language-server \
            && sudo npm update -g bash-language-server \
            || sudo npm install -g bash-language-server
        ;;
    arch)
        sudo pacman -Su --quiet --needed --noconfirm bash-language-server curl gcc neovim python{,-pip} clang cmake ;;
    *)
        echo -e "\e[31m${OS_ID} based distributions are not supported\e[0m" ; exit 126 ;;
esac

[[ -d ~/.vim ]] || {
    mkdir ~/.vim
    mkdir -p ~/.config/nvim
    cat > ~/.config/nvim/init.vim <<'EOF'
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc
EOF
}

python3 -m pip install --user --upgrade pynvim neovim msgpack python-language-server pylint

ln --verbose --force --symbolic --relative "${here}"/.{profile,bash_profile,bashrc,bash_aliases,vimrc,tmux.conf} --target-directory ${HOME}

nvim +PlugUpgrade +PlugInstall +PlugUpdate +UpdateRemotePlugins +GoUpdateBinaries +qa
