#!/bin/bash

set -e

source /etc/os-release

OS_ID=${ID_LIKE:-$ID}

case ${OS_ID} in
    debian)
        sudo apt install --upgrade --quiet -y neovim npm python3{,-pip} gcc
        sudo npm install -g bash-language-server
        ;;
    arch)
        sudo pacman -Su --quiet --needed --noconfirm neovim python pip gcc bash-language-server ;;
    *)
        echo -e "\e[31m${OS_ID} based distributions are not supported\e[0m" ; exit 126 ;;
esac

[[ -d ~/.vim ]] || {
    mkdir ~/.vim
    mkdir -p ~/.config/nvim
    cat > ~/.config/nvim/init.vim <<'EOF'
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc
EOF
}

python3 -m pip install --quiet --user --upgrade pynvim neovim msgpack python-language-server

here="$(dirname "${BASH_SOURCE[0]}")"
ln --verbose --force --symbolic --relative "${here}"/.{profile,bash_profile,bashrc,bash_aliases,vimrc} --target-directory ${HOME}

nvim +PlugUpgrade +PlugInstall +PlugUpdate +UpdateRemotePlugins +qa
